name: deploy-website

on:
  push:
    branches: [ master ]
    paths-ignore:
      .git**
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          name: id_rsa
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Checkout website
        uses: actions/checkout@master
        with:
          path: exult-web-master
      - name: Upload and update website
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          zip -9 master.zip -r exult-web-master &> /dev/null
          ssh -V
          sha1sum ~/.ssh/id_rsa
          ssh-keygen -f ~/.ssh/id_rsa -p -q -N ""
          sha1sum ~/.ssh/id_rsa
          echo scp -i ~/.ssh/id_rsa master.zip ${{ secrets.SCP_HOST }}:${{ secrets.PROJECT_HOME }}
          scp -i ~/.ssh/id_rsa master.zip ${{ secrets.SCP_HOST }}:${{ secrets.PROJECT_HOME }}
          echo ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_HOST }} create
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_HOST }} create
          echo ssh -t -i ~/.ssh/id_rsa ${{ secrets.SSH_HOST }} "cd ${{ secrets.PROJECT_HOME }}; ./update.sh"
          ssh -t -i ~/.ssh/id_rsa ${{ secrets.SSH_HOST }} "cd ${{ secrets.PROJECT_HOME }}; ./update.sh"
          echo ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_HOST }} shutdown
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_HOST }} shutdown
